server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user-reg
    username: root
    password: raja
    driver-class-name: com.mysql.cj.jdbc.Driver
